### ISSUE TITLE
将情感二分类转化为多分类遇到一些问题

### ISSUE THREAD

**Issue by sunyh214** [PaddlePaddle/ERNIE#228]
只需把num_labels给成我所需的类别数吗？还需要做什么？谢谢！

**Comment by OleNet** [comment]
理论上是这样的， 遇到什么问题了吗？

**Comment by haosiqing** [comment]
你好，我在运行sh script/zh_task/ernie_base/run_ChnSentiCorp.sh时报错TypeError: new() missing 1 required positional argument: 'text_a'，
完整报错如下：
Traceback (most recent call last):
File "run_classifier.py", line 403, in 
main(args)
File "run_classifier.py", line 87, in main
phase="train")
File "/mnt/hgfs/share/ERNIE-develop/reader/task_reader.py", line 226, in data_generator
examples = self._read_tsv(input_file)
File "/mnt/hgfs/share/ERNIE-develop/reader/task_reader.py", line 268, in _read_tsv
example = Example(*line)
TypeError: new() missing 1 required positional argument: 'text_a'
好几天了也不会改，请问这是什么原因呢？
