### ISSUE TITLE
运行时报错TypeError: __new__() missing 1 required positional argument: 'text_a'

### ISSUE THREAD

**Issue by haosiqing** [PaddlePaddle/ERNIE#284]
运行sh script/zh_task/ernie_base/run_ChnSentiCorp.sh时报错TypeError: __new__() missing 1 required positional argument: 'text_a'，
完整报错如下：
Traceback (most recent call last):
  File "run_classifier.py", line 403, in <module>
    main(args)
  File "run_classifier.py", line 87, in main
    phase="train")
  File "/mnt/hgfs/share/ERNIE-develop/reader/task_reader.py", line 226, in data_generator
    examples = self._read_tsv(input_file)
  File "/mnt/hgfs/share/ERNIE-develop/reader/task_reader.py", line 268, in _read_tsv
    example = Example(*line)
TypeError: __new__() missing 1 required positional argument: 'text_a'
好几天了也不会改，请问这是什么原因呢？如何得到解决？

**Comment by PROoshio** [comment]
检查下对应的参数是否都配置了

**Comment by yechens** [comment]
如果不是配置的问题，检查一下你的文本里有没有“奇怪”的字符，比如“\t \n”这些；可以先用正则过滤一遍

**Comment by haosiqing** [comment]
> 如果不是配置的问题，检查一下你的文本里有没有“奇怪”的字符，比如“\t \n”这些；可以先用正则过滤一遍
好的我检查一下，感谢您的回复
