### ISSUE TITLE
运行时报错run_ChnSentiCorp.sh:  paddle.fluid.core_avx.EnforceNotMet: Invoke operator mul error.

### ISSUE THREAD

**Issue by SSHLR** [PaddlePaddle/ERNIE#285]
Traceback (most recent call last):
  File "run_classifier.py", line 403, in <module>
    main(args)
  File "run_classifier.py", line 221, in main
    train_exe.run(fetch_list=[])
  File "/data/home/user/anaconda3/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 280, in run
    return_numpy=return_numpy)
  File "/data/home/user/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 666, in run
    return_numpy=return_numpy)
  File "/data/home/user/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 528, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator mul error.

Python Callstacks:
  File "/data/home/user/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "/data/home/user/anaconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/data/home/user/anaconda3/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 334, in fc
    "y_num_col_dims": 1})
  File "/data/home/user/ERNIE/ERNIE-develop/model/transformer_encoder.py", line 60, in __compute_qkv
    bias_attr=name + '_query_fc.b_0')
  File "/data/home/user/ERNIE/ERNIE-develop/model/transformer_encoder.py", line 129, in multi_head_attention
    q, k, v = __compute_qkv(queries, keys, values, n_head, d_key, d_value)
  File "/data/home/user/ERNIE/ERNIE-develop/model/transformer_encoder.py", line 273, in encoder_layer
    name=name + '_multi_head_att')
  File "/data/home/user/ERNIE/ERNIE-develop/model/transformer_encoder.py", line 336, in encoder
    name=name + '_layer_' + str(i))
  File "/data/home/user/ERNIE/ERNIE-develop/model/ernie.py", line 165, in _build_model
    name='encoder')
  File "/data/home/user/ERNIE/ERNIE-develop/model/ernie.py", line 93, in __init__
    input_mask)
  File "/data/home/user/ERNIE/ERNIE-develop/finetune/classifier.py", line 74, in create_model
    use_fp16=args.use_fp16)
  File "run_classifier.py", line 114, in main
    is_regression=args.is_regression)
  File "run_classifier.py", line 403, in <module>
    main(args)

C++ Callstacks:
Enforce failed. Expected posix_memalign(&p, alignment, size) == 0, but received posix_memalign(&p, alignment, size):12 != 0:0.
Alloc 524288000 error! at [/paddle/paddle/fluid/memory/detail/system_allocator.cc:57]
PaddlePaddle Call Stacks:
0       0x7f63d4c2db78p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f63d5ff7337p paddle::memory::detail::AlignedMalloc(unsigned long) + 295
2       0x7f63d5ff75f7p paddle::memory::detail::CPUAllocator::Alloc(unsigned long*, unsigned long) + 39
3       0x7f63d5ff4a0ap paddle::memory::detail::BuddyAllocator::RefillPool(unsigned long) + 58
4       0x7f63d5ff521fp paddle::memory::detail::BuddyAllocator::Alloc(unsigned long) + 719
5       0x7f63d5fd5f05p void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long) + 181
6       0x7f63d5fd6c35p paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long) + 405

情感分类Finetuning时报错，机器配置较差，只用CPU  (6核， 32G内存)， 跑的1.0版本，这里报错是因为配置不够吗？可以通过设置降低参数把代码跑通吗？

**Comment by zhanghan1992** [comment]
可以减小batch_size

**Comment by SSHLR** [comment]
好的，batch_size减小到10，勉强可以，谢谢
