### ISSUE TITLE
运行ChnSentiCorp报错

### ISSUE THREAD

**Issue by lionel-xie** [PaddlePaddle/ERNIE#295]
-----------  Configuration Arguments -----------
batch_size: 24
checkpoints: ./checkpoints
chunk_scheme: IOB
dev_set: D:/Ѹ▒▒▒▒▒▒/ERNIE-develop/ERNIE-develop/task_data//chnsenticorp/dev.tsv,D:/Ѹ▒▒▒▒▒▒/ERNIE-develop/ERNIE-develop/task_data//chnsenticorp/test.tsv
diagnostic: None
diagnostic_save: None
do_lower_case: True
do_test: False
do_train: True
do_val: True
doc_stride: 128
enable_ce: False
epoch: 10
ernie_config_path: D:/Ѹ▒▒▒▒▒▒/ERNIE-develop/ERNIE-develop/ERNIE_1.0_max-len-512/ernie_config.json
for_cn: True
in_tokens: False
init_checkpoint: None
init_pretraining_params: D:/Ѹ▒▒▒▒▒▒/ERNIE-develop/ERNIE-develop/ERNIE_1.0_max-len-512/params
is_classify: True
is_regression: False
label_map_config: None
learning_rate: 5e-05
loss_scaling: 1.0
lr_scheduler: linear_warmup_decay
max_answer_length: 100
max_query_length: 64
max_seq_len: 256
metric: simple_accuracy
metrics: True
n_best_size: 20
num_iteration_per_drop_scope: 1
num_labels: 2
predict_batch_size: None
random_seed: 1
save_steps: 1000
shuffle: True
skip_steps: 10
task_id: 0
test_save: test_result
test_set: None
tokenizer: FullTokenizer
train_set: D:/Ѹ▒▒▒▒▒▒/ERNIE-develop/ERNIE-develop/task_data//chnsenticorp/train.tsv
use_cuda: True
use_fast_executor: False
use_fp16: False
use_multi_gpu_test: False
validation_steps: 100
verbose: True
vocab_path: D:/Ѹ▒▒▒▒▒▒/ERNIE-develop/ERNIE-develop/ERNIE_1.0_max-len-512/vocab.txt
warmup_proportion: 0.0
weight_decay: 0.01
------------------------------------------------
attention_probs_dropout_prob: 0.1
hidden_act: relu
hidden_dropout_prob: 0.1
hidden_size: 768
initializer_range: 0.02
max_position_embeddings: 513
num_attention_heads: 12
num_hidden_layers: 12
type_vocab_size: 2
vocab_size: 18000
------------------------------------------------
Device count: 1
Num train examples: 9600
Max train steps: 4000
Num warmup steps: 0
Theoretical memory usage in training: 28739.403 - 30107.946 MB
Traceback (most recent call last):
  File "run_classifier.py", line 403, in <module>
    main(args)
  File "run_classifier.py", line 169, in main
    use_fp16=args.use_fp16)
  File "D:\Ѹ▒▒▒▒▒▒\ERNIE-develop\ERNIE-develop\utils\init.py", line 76, in init_pretraining_params
    predicate=existed_params)
  File "E:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 611, in load_vars
    filename=filename)
  File "E:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 648, in load_vars
    executor.run(load_prog)
  File "E:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "E:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator load error.
Python Callstacks:
  File "E:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "E:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 633, in load_vars
    'file_path': os.path.join(load_dirname, new_var.name)
  File "E:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 611, in load_vars
    filename=filename)
  File "D:\Ѹ▒▒▒▒▒▒\ERNIE-develop\ERNIE-develop\utils\init.py", line 76, in init_pretraining_params
    predicate=existed_params)
  File "run_classifier.py", line 169, in main
    use_fp16=args.use_fp16)
  File "run_classifier.py", line 403, in <module>
    main(args)
C++ Callstacks:
Cannot open file D:\Ѹ▒▒▒▒▒▒\ERNIE-develop\ERNIE-develop\ERNIE_1.0_max-len-512\params\word_embedding for load op at [D:/1.5.1/release_cuda97/paddle\paddle/fluid/operators/load_op.h:37]
PaddlePaddle Call Stacks:
Windows not support stack backtrace yet.
W0825 18:51:26.312366  4412 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 9.0
W0825 18:51:26.333367  4412 device_context.cc:267] device: 0, cuDNN Version: 7.4.
(paddle)

**Comment by zhanghan1992** [comment]
当前暂不支持windows系统。可以在windows系统下通过docker使用ERNIE。
