### ISSUE TITLE
阅读理解 drcd报错 在一轮训练结束的时候报错。

### ISSUE THREAD

**Issue by natureLanguageQing** [PaddlePaddle/ERNIE#299]
Traceback (most recent call last):
  File "run_mrc.py", line 325, in <module>
    main(args)
  File "run_mrc.py", line 251, in main
    args=args)
  File "/home/aistudio/work/ERNIE/finetune/mrc.py", line 177, in evaluate
    em, f1, avg, total = eval_file(data_file, output_prediction_file)
  File "/home/aistudio/work/ERNIE/utils/cmrc2018_eval.py", line 140, in eval_file
    ground_truth_file = json.load(open(dataset_file, 'rb'))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
terminate called without an active exception
Aborted (core dumped)
因为我不会用windows启动shell脚本，所以不会改。

**Comment by ak47-1234** [comment]
切换python2.7

**Comment by ak47-1234** [comment]
你可以将
utils/cmrc2018_eval.py里的
ground_truth_file = json.load(open(dataset_file, 'rb'))
prediction_file = json.load(open(prediction_file, 'rb'))
rb改为r

**Comment by ak47-1234** [comment]
你可以将
utils/cmrc2018_eval.py里的
ground_truth_file = json.load(open(dataset_file, 'rb'))
prediction_file = json.load(open(prediction_file, 'rb'))
rb改为r

**Comment by natureLanguageQing** [comment]
为什么不把分词换成jieba 用nltk的直接跑会报错

**Comment by ak47-1234** [comment]
nltk会报什么错？提供一下错误

**Comment by natureLanguageQing** [comment]
好吧，我换成了结巴

**Comment by natureLanguageQing** [comment]
好吧我切换到了python2.7

**Comment by natureLanguageQing** [comment]
代码注释问题和对象命名问题能不能搞一下。这是我见过命名最差的开源代码
