### ISSUE TITLE
RuntimeError: know type float64

### ISSUE THREAD

**Issue by lunlu** [PaddlePaddle/ERNIE#385]
问题详情：
```script
Task exception was never retrieved
future: <Task finished coro=<InferenceClient.__call__.<locals>.get() done, defined at /home/tianlun/tools/ERNIE/ERNIE-develop/propeller/service/client.py:77> exception=RuntimeError('know type float64',)>
Traceback (most recent call last):
  File "/home/tianlun/tools/ERNIE/ERNIE-develop/propeller/service/client.py", line 84, in get
    request = serv_utils.nparray_list_serialize(arr_list)
  File "/home/tianlun/tools/ERNIE/ERNIE-develop/propeller/service/utils.py", line 105, in nparray_list_serialize
    slot_list = [numpy_to_slot(arr) for arr in arr_list]
  File "/home/tianlun/tools/ERNIE/ERNIE-develop/propeller/service/utils.py", line 105, in <listcomp>
    slot_list = [numpy_to_slot(arr) for arr in arr_list]
  File "/home/tianlun/tools/ERNIE/ERNIE-develop/propeller/service/utils.py", line 55, in numpy_to_slot
    raise RuntimeError('know type %s' % arr.dtype)
RuntimeError: know type float64
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    ret = client(query)
  File "/home/tianlun/tools/ERNIE/ERNIE-develop/ernie/service/client.py", line 79, in __call__
    ret, = super(ErnieClient, self).__call__(sen_ids, token_type_ids)
  File "/home/tianlun/tools/ERNIE/ERNIE-develop/propeller/service/client.py", line 102, in __call__
    raise RuntimeError('Client call failed')
RuntimeError: Client call failed
```
向量化请求，前面的n条一直成功，突然失败了，为什么，失败处的数据单独拿出来请求没有问题。

**Comment by Meiyim** [comment]
请问使用的paddle版本、numpy版本为多少。
