### ISSUE TITLE
load inference model之后执行预测时报错"should be Variable or str"

### ISSUE THREAD

**Issue by thuwangzhe** [PaddlePaddle/ERNIE#440]
用save_inference_model的方式保存了模型文件，在执行预测时加载模型:
```python
[self.predict_prog, self.feed_target_names, self.fetch_targets] = (fluid.io.load_inference_model(dirname=args.init_checkpoint, executor=self.exe))
self.predict_exe = fluid.ParallelExecutor(
            use_cuda=args.use_cuda, main_program=self.predict_prog)
np_vecs = self.predict_exe.run(fetch_list=[self.fetch_targets])
```

之后报错
```bash
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    main()
  File "main.py", line 81, in main
    predictor.process_file(input_filename,input_filename+'.txt')
  File "/home/disk0/wangzhe23/qb_shuangta_12_128/predict.py", line 100, in process_file
    np_vecs = self.predict_exe.run(fetch_list=[self.fetch_targets])
  File "/home/disk0/wangzhe23/tools/python27_paddle_1.5.0/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 280, in run
    return_numpy=return_numpy)
  File "/home/disk0/wangzhe23/tools/python27_paddle_1.5.0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 665, in run
    return_numpy=return_numpy)
  File "/home/disk0/wangzhe23/tools/python27_paddle_1.5.0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 526, in _run_parallel
    fetch_var_names = list(map(_to_name_str, fetch_list))
  File "/home/disk0/wangzhe23/tools/python27_paddle_1.5.0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 247, in _to_name_str
    raise TypeError(str(var) + " should be Variable or str")
TypeError: [name: "save_infer_model/scale_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
    }
    lod_level: 0
  }
}
persistable: false
] should be Variable or str
```

这个save_infer_model/scale_0输出的向量就是我需要的output向量，不知道为什么会有这样的错误，排查了很久没有解决，辛苦review一下是哪里的问题

**Comment by baiyfbupt** [comment]
确认一下类型
print(type(self.fetch_targets))
确保self.fetch_targets是variable或者str，而不是list of variables或list of strs

**Comment by thuwangzhe** [comment]
您好，self.fetch_targets是list类型。
我的保存方式是
```python
pyreader, probs, feed_target_name = create_model(
                args,
                pyreader_name='predict_reader',
                ernie_config=ernie_config,
                is_prediction=True)

fluid.io.save_inference_model(
            model_path,
            feed_target_name, probs,
            exe,
            main_program=predict_prog)
```
上面的self.fetch_targets应该是对应着probs，probs的内容为bert模型最后的全连接输出，即create_model的第二个返回值：
```python
query_vec = layers.fc(
        input=query_cls_vec_drop,
        size=128,
        act='tanh',
        param_attr=fluid.ParamAttr(
            name="query_proj_w",
            initializer=fluid.initializer.TruncatedNormal(scale=0.02)),
        bias_attr=fluid.ParamAttr(
            name="query_proj_b", initializer=fluid.initializer.Constant(0.)))

    feed_targets_name = [
        query_src_ids.name, query_pos_ids.name, query_sent_ids.name, query_input_mask.name
    ]
    return pyreader, **query_vec**, feed_targets_name
```
我自己觉得并没有把这个变量保存为list，应该就是variable，请问是哪里出的问题呢

**Comment by baiyfbupt** [comment]
>您好，self.fetch_targets是list类型。

self.fetch_targets是list，那下面这里传给fetch_list的是list of list [[]]？这样类型是不对的，去掉下面的括号[]试试？

> np_vecs = self.predict_exe.run(fetch_list=[self.fetch_targets])

**Comment by thuwangzhe** [comment]
去掉了[]，报了如下的错误：
```bash
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    main()
  File "main.py", line 81, in main
    predictor.process_file(input_filename,input_filename+'.txt')
  File "/home/disk0/wangzhe23/qb_shuangta_12_128/predict.py", line 102, in process_file
    np_vecs = self.predict_exe.run(fetch_list=self.fetch_targets)
  File "/home/disk0/wangzhe23/tools/python27_paddle_1.5.0/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 280, in run
    return_numpy=return_numpy)
  File "/home/disk0/wangzhe23/tools/python27_paddle_1.5.0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 665, in run
    return_numpy=return_numpy)
  File "/home/disk0/wangzhe23/tools/python27_paddle_1.5.0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 527, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator feed error.
Python Callstacks:
  File "/home/disk0/wangzhe23/tools/python27_paddle_1.5.0/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1819, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/home/disk0/wangzhe23/tools/python27_paddle_1.5.0/lib/python2.7/site-packages/paddle/fluid/io.py", line 883, in prepend_feed_ops
    attrs={'col': i})
  File "/home/disk0/wangzhe23/tools/python27_paddle_1.5.0/lib/python2.7/site-packages/paddle/fluid/io.py", line 1065, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "./gen_inference_model.py", line 97, in main
    main_program=predict_prog)
  File "./gen_inference_model.py", line 102, in <module>
    main(args)
C++ Callstacks:
Enforce failed. Expected static_cast<size_t>(col) < feed_list.size(), but received static_cast<size_t>(col):3 >= feed_list.size():0.
 at [/paddle/paddle/fluid/operators/controlflow/feed_op.cc:53]
PaddlePaddle Call Stacks:
0       0x7f738daa8bc8p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f738daa8f17p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f738f4ac48ap paddle::operators::FeedOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 3050
3       0x7f738fa032dcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
4       0x7f738f7ffa2ap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
5       0x7f738f7f23d0p paddle::framework::details::OpHandleBase::Run(bool) + 160
6       0x7f738f7d3746p paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 310
7       0x7f738f7d23afp paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*) + 47
8       0x7f738f7d276fp
9       0x7f738dcdcb43p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
10      0x7f738db73787p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
11      0x7f73e00dc973p pthread_once + 83
12      0x7f738f7cddf2p
13      0x7f738db74d04p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
14      0x7f73b42b58a0p
15      0x7f73e00d71c3p
16      0x7f73df6ff12dp clone + 109
```

**Comment by baiyfbupt** [comment]
> Enforce failed. Expected static_cast<size_t>(col) < feed_list.size(), but received static_cast<size_t>(col):3 >= feed_list.size():0.

看log是feed出了问题，exe.run的时候是否有feed数据呢？

**Comment by thuwangzhe** [comment]
有的，使用的是py_reader方式来feed数据：
processor = reader.GenVecProcessor(filename,
                                           self.args.vocab_path,
                                           self.args.max_query_len,
                                           self.args.max_title_len,
                                           self.args.in_tokens,
                                           self.args.wordseg_worddict_dir,
                                           is_query=self.is_query)

        self.predict_pyreader.decorate_tensor_provider(
            processor.data_generator(
                batch_size=self.args.batch_size, epoch=1, shuffle=False))

        self.predict_pyreader.start()
py_reader也是在create_model时构建：
pyreader = layers.py_reader(
        capacity=50,
        shapes=[[-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, args.max_seq_len], [-1, 1]],
        dtypes=['int64', 'int64', 'int64', 'float', 'int64'],
        lod_levels=[0, 0, 0, 0, 0],
        name=pyreader_name,
        use_double_buffer=True)

    (src_ids, pos_ids, sent_ids, attn_mask, next_sent_index) = layers.read_file(pyreader)
