### ISSUE TITLE
Cuda error(77), an illegal memory access was encountered.

### ISSUE THREAD

**Issue by jtyoui** [PaddlePaddle/ERNIE#466]
`140it [03:24,  1.25s/it]train loss 0.00011
150it [03:39,  1.63s/it]train loss 0.00007
160it [03:55,  1.49s/it]train loss 0.00009
166it [04:03,  1.33s/it]Traceback (most recent call last):
  File "es.py", line 85, in <module>
    opt.minimize(loss)
  File "</usr/local/lib/python3.6/site-packages/decorator.py:decorator-gen-65>", line 2, in minimize
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 273, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 837, in minimize
    loss, startup_program=startup_program, params_grads=params_grads)
  File "/usr/local/lib/python3.6/site-packages/ernie/optimization.py", line 158, in apply_optimize
    L.assign(p * (1. - self.wd * self.current_step_lr()), p)
  File "</usr/local/lib/python3.6/site-packages/decorator.py:decorator-gen-62>", line 2, in current_step_lr
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 216, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 349, in current_step_lr
    if current_lr:
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 215, in __bool__
    return self.__nonzero__()
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 212, in __nonzero__
    return bool(np.all(tensor.__array__() > 0))
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(77), an illegal memory access was encountered.
  [Advise: The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:281)

`

**Comment by Meiyim** [comment]
这个问题的确偶然会出现；仍在定位中

**Comment by nvliajia** [comment]
> 这个问题的确偶然会出现；仍在定位中
老哥，不是偶然啊，我今天一上午总是出现这错误。和GPU内存大小有关系吗

**Comment by Meiyim** [comment]
跟显存应该关系不大
目测是 softmax_with_cross_entropy 这个api输入label为-100时会越界，即使-100被指定为了ignore_index也有越界行为。

目前需要暂时避免使用ignore_index

**Comment by nvliajia** [comment]
我一直报这个错误，还没训练成功过，有什么方法么

**Comment by Meiyim** [comment]
在上面的PR中规避了memory越界问题；仍然有任何问题的话随时reopen这个issue

**Comment by Pacerzhujiang0112** [comment]
又出现了这样的问题！！！
Traceback (most recent call last):
  File "msraner.py", line 163, in <module>
    loss, logits = model(ids, sids, labels=aligned_label, loss_weights=L.cast(ids > tokenizer.mask_id, 'float32')) # [MASK] is the largest special token
  File "/home/zhu/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhu/下载/ERNIE/ernie/modeling_ernie.py", line 424, in forward
    pooled, encoded = super(ErnieModelForTokenClassification, self).forward(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'loss_weights'

**Comment by nvliajia** [comment]
感谢，可以训练了。但是在我的数据集上训练结果不如Bert，比BiLSTM+CRF好点

**Comment by paulpaul91** [comment]
> 跟显存应该关系不大
> 目测是 softmax_with_cross_entropy 这个api输入label为-100时会越界，即使-100被指定为了ignore_index也有越界行为。
> 
> 目前需要暂时避免使用ignore_index

请问新版本有没有解决这个问题
