### ISSUE TITLE
机器阅读理解任务demo报错AttributeError: 'NoneType' object has no attribute 'nranks'

### ISSUE THREAD

**Issue by leo038** [PaddlePaddle/ERNIE#477]
执行脚本：
python3 ./ERNIE-develop/demo/finetune_mrc_dygraph.py --from_pretrained ./pretrain_model/    --train_file  ./cmrc2018/train/train.json  --dev_file  ./cmrc2018/dev/dev.json

报错信息：
Traceback (most recent call last):
  File "./ERNIE-develop/demo/finetune_mrc_dygraph.py", line 169, in <module>
    train(model, train_dataset, dev_dataset, dev_examples, dev_features, tokenizer, args)
  File "./ERNIE-develop/demo/finetune_mrc_dygraph.py", line 97, in train
    scaled_loss = model.scale_loss(loss)
  File "/home/xxx/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/parallel.py", line 333, in scale_loss
    if not self._is_data_parallel_mode():
  File "/home/xxx/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/parallel.py", line 457, in _is_data_parallel_mode
    return self._strategy.nranks > 1
AttributeError: 'NoneType' object has no attribute 'nranks'

**Comment by Meiyim** [comment]
请使用paddle.distributed.launch启动多卡训练，用法参见readme（阅读理解系列任务因为max sequence length 过长导致单卡batch较小，为达到应有的batch size 通常需要多卡训练）

这里readme应该加以注明。

**Comment by leo038** [comment]
Thank you, I will try it!
