### ISSUE TITLE
ernie动态图，按照说明运行微调示例，报错KeyError: b'entailment\r'

### ISSUE THREAD

**Issue by lerry-lee** [PaddlePaddle/ERNIE#497]
使用 动态图 模型进行finetune:
```
python3 ./demo/finetune_classifier_dygraph.py \
       --from_pretrained ernie-1.0 \
       --data_dir ./data/xnli  
```
结果报错
```
training: 0it [00:00, ?it/s][ERROR] 2020-06-15 15:14:58,971 [functional.py:   69]:      b'entailment\r'
Traceback (most recent call last):
  File "D:\project\nlp\ERNIE\demo\propeller\paddle\data\functional.py", line 66, in _gen
    for idx, i in enumerate(self.generator()):
  File "D:\project\nlp\ERNIE\demo\propeller\data\functional.py", line 282, in _wrapper
    for item in _gen():
  File "D:\project\nlp\ERNIE\demo\propeller\data\functional.py", line 240, in _gen
    buf = list(itertools.islice(iterable, batch_size))
  File "D:\project\nlp\ERNIE\demo\propeller\data\functional.py", line 282, in _wrapper
    for item in _gen():
  File "D:\project\nlp\ERNIE\demo\propeller\data\functional.py", line 135, in _gen
    for i in dataset():
  File "D:\project\nlp\ERNIE\demo\propeller\data\functional.py", line 282, in _wrapper
    for item in _gen():
  File "D:\project\nlp\ERNIE\demo\propeller\data\functional.py", line 139, in _gen
    yield fn(i)
  File "D:\project\nlp\ERNIE\demo\propeller\paddle\data\feature_column.py", line 371, in _parse_txt_file
    for feature, column in zip(features, self._columns)
  File "D:\project\nlp\ERNIE\demo\propeller\paddle\data\feature_column.py", line 371, in <listcomp>
    for feature, column in zip(features, self._columns)
  File "D:\project\nlp\ERNIE\demo\propeller\paddle\data\feature_column.py", line 127, in raw_to_instance
    ids = self.vocab[raw]
KeyError: b'entailment\r'
2020-06-15 15:14:58,972-WARNING: DygraphDataLoader reader thread raised an exception.
training: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "./demo/finetune_classifier_dygraph.py", line 119, in <module>
    for step, d in enumerate(tqdm(train_ds.start(place), desc='training')):
  File "C:\Users\LERRY\Anaconda3\envs\ernie\lib\site-packages\tqdm\std.py", line 1129, in __iter__
    for obj in iterable:
  File "C:\Users\LERRY\Anaconda3\envs\ernie\lib\site-packages\paddle\fluid\reader.py", line 804, in __next__
    return self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (D:\1.8.1\paddle\paddle/fluid/operators/reader/blocking_queue.h:141)

```

**Comment by Meiyim** [comment]
目测是windwos的 文件格式问题；
建议你重新下载一遍训练数据；不要用windows的文本编辑器打开它（否则可能插入奇怪的字符`\r\n`一类的）；直接跑ERNIE-finetune看可否解决。

**Comment by lerry-lee** [comment]
@Meiyim 谢谢~我在linux上使用下载的原始数据可以正常fine_tune
但是在windows还是不行，报错如下
```
training: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "./demo/finetune_classifier_dygraph.py", line 121, in <module>
    loss, _ = model(ids, sids, labels=label)
  File "C:\Users\LERRY\Anaconda3\envs\ernie\lib\site-packages\paddle\fluid\dygraph\layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\project\nlp\ERNIE\demo\ernie\modeling_ernie.py", line 391, in forward
    loss = L.softmax_with_cross_entropy(logits, labels)
  File "C:\Users\LERRY\Anaconda3\envs\ernie\lib\site-packages\paddle\fluid\layers\loss.py", line 1256, in softmax_with_cross_entropy
    axis)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] at (D:\1.8.1\paddle\paddle/fluid/framework/tensor_impl.h:33)
```
ernie动态图是不支持windows平台吗？

**Comment by lerrylca** [comment]
另外，先启动了xnli数据集的inference_model，在linux上调用示例中的预测服务
```
from propeller.service.client import InferenceClient
from ernie.tokenizing_ernie import ErnieTokenizer

client = InferenceClient('tcp://localhost:8881')
tokenizer = ErnieTokenizer.from_pretrained('ernie-1.0')
ids, sids = tokenizer.encode('hello world')
ids = np.expand_dims(ids, 0)
sids = np.expand_dims(sids, 0)
result = client(ids, sids)
```
返回结果为
```
[array([[-0.0460582 ,  0.28323928, -0.00521138]], dtype=float32)]
```
这个numpy array代表了什么含义呢？

**Comment by Meiyim** [comment]
应该来说，目前还没有针对windows平台测试过。但是理论上来说既然paddle能支持windows，ernie就能支持windows平台。
目前可能会遇到一些细节问题，但是应该可以轻易修复。

你截图的这个问题目测是labels的dtype不为np.int64, 你可以在[这里](https://github.com/PaddlePaddle/ERNIE/blob/develop/demo/finetune_classifier_dygraph.py#L81)加一些log确认一下 labels的dtype，或者手动cast下看可否解决。
