### ISSUE TITLE
NER recognition

### ISSUE THREAD

**Issue by sasuke96** [PaddlePaddle/ERNIE#520]
Hi 
 I was getting assertion error while using ernie on my own data .I was able to run it for MSRA NER data
i did the pre processing on my text of removing null values converting it to utf-8 and saving it as tsv file

 warnings.warn("Caution! 'set_gradient_clip' is not recommended "
[INFO] 2020-07-11 06:44:08,114 [     init.py:   88]:	Load pretraining parameters from /axp/rim/emvgml/dev/Vishesh/ernie/ernie_gen_large/params.
Traceback (most recent call last):
  File "/axp/rim/emvgml/dev/Vishesh/ernie/ERNIE-repro/ernie/reader/task_reader.py", line 270, in f
    for i in wrapper():
  File "/axp/rim/emvgml/dev/Vishesh/ernie/ERNIE-repro/ernie/reader/task_reader.py", line 261, in wrapper
    examples, batch_size, phase=phase):
  File "/axp/rim/emvgml/dev/Vishesh/ernie/ERNIE-repro/ernie/reader/task_reader.py", line 223, in _prepare_batch_data
    self.tokenizer)
  File "/axp/rim/emvgml/dev/Vishesh/ernie/ERNIE-repro/ernie/reader/task_reader.py", line 403, in _convert_example_to_record
    tokens, labels = self._reseg_token_label(tokens, labels, tokenizer)
  File "/axp/rim/emvgml/dev/Vishesh/ernie/ERNIE-repro/ernie/reader/task_reader.py", line 397, in _reseg_token_label
    assert len(ret_tokens) == len(ret_labels)
AssertionError
/adshome/vgupt137/.local/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")

**Comment by Meiyim** [comment]
Maybe the label you provided in train file doesn't match one of these branches: https://github.com/PaddlePaddle/ERNIE/blob/repro/ernie/reader/task_reader.py#L383

you can change this line: https://github.com/PaddlePaddle/ERNIE/blob/repro/ernie/reader/task_reader.py#L383 to:
```python
assert len(ret_tokens) == len(ret_labels), repr(labels)
```
and see if your label starts with "O"/"B-"/"I-"/"E-"/"S-"

**Comment by sasuke96** [comment]
for example
token=['Yes please . That would be fantastic .']
labels=['O O O O O O O O']
ret_tokens=['yes', 'please', '.', 'that', 'would', 'be', 'fantastic', '.']
but 
ret_labels=[]
i don't understand why it is not reading 'O'

but if example is 
token=['Yes']
label=['O']

ret_token=['Yes']
ret_label=['O']

it is not able to read multiple 'O' label


the error is in the label ['o o'] but it is already defined in my label_map_config _file


 warnings.warn("Caution! 'set_gradient_clip' is not recommended "
[INFO] 2020-07-13 04:30:26,194 [     init.py:   88]:	Load pretraining parameters from /axp/rim/emvgml/dev/Vishesh/ernie/ernie_gen_large/params.
Traceback (most recent call last):
  File "/axp/rim/emvgml/dev/Vishesh/ernie/ERNIE-repro/ernie/reader/task_reader.py", line 270, in f
    for i in wrapper():
  File "/axp/rim/emvgml/dev/Vishesh/ernie/ERNIE-repro/ernie/reader/task_reader.py", line 261, in wrapper
    examples, batch_size, phase=phase):
  File "/axp/rim/emvgml/dev/Vishesh/ernie/ERNIE-repro/ernie/reader/task_reader.py", line 223, in _prepare_batch_data
    self.tokenizer)
  File "/axp/rim/emvgml/dev/Vishesh/ernie/ERNIE-repro/ernie/reader/task_reader.py", line 404, in _convert_example_to_record
    tokens, labels = self._reseg_token_label(tokens, labels, tokenizer)
  File "/axp/rim/emvgml/dev/Vishesh/ernie/ERNIE-repro/ernie/reader/task_reader.py", line 398, in _reseg_token_label
    assert len(ret_tokens) == len(ret_labels), repr(labels)
AssertionError: ['O O']
/adshome/vgupt137/.local/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):

**Comment by Meiyim** [comment]
The default delimeter of NER train file is `b'\2'`(ascii code 2), see [here](https://github.com/PaddlePaddle/ERNIE/blob/repro/ernie/reader/task_reader.py#L401). This token can't be properly rendered by github, so it's a little bit misleading.

Make sure you provided the right delimeter in you customized train/dev/test file.

**Comment by sasuke96** [comment]
Hi Thanks
It worked i had to change this and put space as delimiter
