### ISSUE TITLE
AiStudio环境，python3.7，paddle1.8.0，ernie报错如下

### ISSUE THREAD

**Issue by hlzonWang** [PaddlePaddle/ERNIE#534]
Traceback (most recent call last):
  File "make_pretrain_data.py", line 126, in <module>
    from ernie.tokenizing_ernie import _wordpiece
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ernie/__init__.py", line 4, in <module>
    from .ernie import *
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ernie/ernie.py", line 6, in <module>
    from transformers import (
ImportError: cannot import name 'AutoModel' from 'transformers' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/transformers/__init__.py)

**Comment by Meiyim** [comment]
你是不是装错包了。。。本repo的pypi项目名是`paddle_ernie`而不是`ernie`

**Comment by hlzonWang** [comment]
> 你是不是装错包了。。。本repo的pypi项目名是`paddle_ernie`而不是`ernie`

真是装错包了。。谢谢大佬哈
