### ISSUE TITLE
使用CPU进行predict过程的问题

### ISSUE THREAD

**Issue by XinLiu-cs** [PaddlePaddle/ERNIE#56]
用GPU进行了finetune过程的模型想用CPU进行推理是否还需要指定CUDA_VISIBLE_DEVICES，若不指定，将use_cuda设定为False后报错为：
```
Traceback (most recent call last):
  File "predict_classifier.py", line 153, in <module>
    main(args)
  File "predict_classifier.py", line 104, in main
    exe.run(predict_startup)
  File "/****/lib/python2.7/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: no CUDA-capable device is detected at [/paddle/paddle/fluid/platform/gpu_info.cc:65]
```
若指定CUDA_VISIBLE_DEVICES，在预测过程中predict_pyreader直接抛出fluid.core.EOFException，不对数据进行处理。

**Comment by tianxin1860** [comment]
用 CPU 进行推理的话，注意需要安装 **CPU** 版本的 paddlepaddle，不需要指 CUDA_VISIBLE_DEVICES
```
pip install paddlepaddle （CPU版本最新）
pip install paddlepaddle-gpu （GPU版本最新）
```

**Comment by XinLiu-cs** [comment]
好的
