### ISSUE TITLE
ERNIE-GAN迁移学习，无法读取自制数据集

### ISSUE THREAD

**Issue by herb711** [PaddlePaddle/ERNIE#576]
在进行迁移学习时，使用官网的 NLPCC2016问答数据集 ，可以正常进行迁移学习

但是使用同样格式的自制数据集，进行训练时，就会报错。（**特别强调**，自制数据集已经调整到用txt打开后从肉眼上看，和官网数据集一模一样）

对比过自制数据集和# NLPCC2016问答数据集 的格式和区别。感觉没有不同。

将 # NLPCC2016问答数据集 重新读入，再写成文件，也会报错。

当然，这个不是ERNIE-GAN本身的问题。但是格式一致的文件。为什么，读取的时候，会有区别呢？希望帮忙答复。

这是读写数据的代码（将NLPCC2016里的数据读出来，一点不改，然后写到新的文件里面去）
```
def readdata(myfile, data_name):
    with open(data_name, 'w', encoding='utf-8') as fw:
        with open(myfile, 'r', encoding='utf-8') as f:
            line = f.readline()
            print(line)
            while line:
                fw.writelines(line)
                line = f.readline()
```

这是自制数据集时的程序（也是用过直接读取文件的方法，但是也是不行）
```
import json, random
import codecs

def makedata_zhongyi(json_dir, data_name):
    with open(json_dir, 'r', encoding='UTF-8') as f:
        train_datas = json.load(f)

        with codecs.open(data_name, 'w', "utf-8") as f:
            for data in train_datas:
                for text in data['annotations']:
                    Q = text['Q'].replace('\n', '')
                    A = text['A'].replace('\n', '')         
                    rows = '1' +'\t'+ Q +'\t'+ A +'\n'
                    f.writelines(rows.replace(' ', ''))
```

**Comment by zhanghan1992** [comment]
报什么错？

**Comment by herb711** [comment]
[INFO] 2020-09-29 18:04:15,741 [modeling_ernie.py:  214]:	loading pretrained model from /tmp/466eabcffd6d6a83ae9cb97dd1a167bd
[INFO] 2020-09-29 18:04:18,942 [feature_column.py:  353]:	reading raw files from work/doctor-data/train/1
work/doctor-data/train/.ipynb_checkpoints
[INFO] 2020-09-29 18:04:18,944 [feature_column.py:  353]:	reading raw files from work/doctor-data/dev/1
work/doctor-data/dev/.ipynb_checkpoints
[ERROR] 2020-09-29 18:04:18,948 [functional.py:   69]:	[Errno 21] Is a directory: 'work/doctor-data/train/.ipynb_checkpoints'
Traceback (most recent call last):
  File "./ERNIE/propeller/paddle/data/functional.py", line 66, in _gen
    for idx, i in enumerate(self.generator()):
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 135, in _gen
    for i in dataset():
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 240, in _gen
    buf = list(itertools.islice(iterable, batch_size))
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 74, in _gen
    buf.append(next(iterable))
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 135, in _gen
    for i in dataset():
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 135, in _gen
    for i in dataset():
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 99, in _gen
    for tup in six.moves.zip_longest(*buf):
  File "./ERNIE/propeller/data/functional.py", line 96, in <genexpr>
    j = (jjj for jj in j for jjj in jj)  #flatten
  File "./ERNIE/propeller/data/functional.py", line 301, in _gen
    with _open_file(filename, format) as f:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "./ERNIE/propeller/data/functional.py", line 45, in _open_file
    fd = open(filename, 'rb')
IsADirectoryError: [Errno 21] Is a directory: 'work/doctor-data/train/.ipynb_checkpoints'
[WARNING] 2020-09-29 18:04:18,950 [   reader.py:  912]:	DygraphDataLoader reader thread raised an exception.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 913, in _reader_thread_loop_for_singleprocess
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 892, in _reader_thread_loop_for_singleprocess
    for sample in self._batch_reader():
  File "./ERNIE/propeller/paddle/data/functional.py", line 70, in _gen
    raise e
  File "./ERNIE/propeller/paddle/data/functional.py", line 66, in _gen
    for idx, i in enumerate(self.generator()):
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 135, in _gen
    for i in dataset():
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 240, in _gen
    buf = list(itertools.islice(iterable, batch_size))
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 74, in _gen
    buf.append(next(iterable))
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 135, in _gen
    for i in dataset():
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 135, in _gen
    for i in dataset():
  File "./ERNIE/propeller/data/functional.py", line 282, in _wrapper
    for item in _gen():
  File "./ERNIE/propeller/data/functional.py", line 99, in _gen
    for tup in six.moves.zip_longest(*buf):
  File "./ERNIE/propeller/data/functional.py", line 96, in <genexpr>
    j = (jjj for jj in j for jjj in jj)  #flatten
  File "./ERNIE/propeller/data/functional.py", line 301, in _gen
    with _open_file(filename, format) as f:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "./ERNIE/propeller/data/functional.py", line 45, in _open_file
    fd = open(filename, 'rb')
IsADirectoryError: [Errno 21] Is a directory: 'work/doctor-data/train/.ipynb_checkpoints'

---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-16-ad4d96e4e899> in <module>
     31 attn_id = tokenizer.vocab[ATTN_TOKEN]
     32 
---> 33 for step, data in enumerate(train_ds.start(place)):
     34     print(data)
     35 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py in __next__(self)
    802     def __next__(self):
    803         try:
--> 804             return self._reader.read_next_var_list()
    805         except StopIteration:
    806             self._reset()
EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

**Comment by herb711** [comment]
> 报什么错？

见跟帖

**Comment by herb711** [comment]
> 报什么错？

大神，还请帮助解答一下，报错信息已经贴出来了。

**Comment by zhanghan1992** [comment]
work/doctor-data/train/.ipynb_checkpoints 这个目录是怎么产出的？

**Comment by herb711** [comment]
> work/doctor-data/train/.ipynb_checkpoints 这个目录是怎么产出的？

work/doctor-data/train 这个目录是我自己建立的，代码是在studio平台上运行的。

**Comment by herb711** [comment]
问题已解决。是目录下面存在隐藏文件 .ipynb_checkpoints
