### ISSUE TITLE
ernie-gen SQuAD finetuning error

### ISSUE THREAD

**Issue by cberrioa** [PaddlePaddle/ERNIE#695]
Hi, I'm having some problems while trying to finetune ernie-gen on SQuAD. Here are the logs:

```
-----------  Configuration Arguments -----------
attention_probs_dropout_prob: -1.0
batch_size: 1
beam_size: 1
checkpoints: ./checkpoints
continuous_position: True
decr_every_n_nan_or_inf: 2
decr_ratio: 0.8
dev_set: ./datasets/squad_qg//dev.tsv
do_decode: True
do_lower_case: True
do_pred: False
do_test: False
do_train: True
do_val: False
epoch: 10
ernie_config_path: ernie_gen_base/ernie_config.json
eval_mertrics: Bleu_4,METEOR,ROUGE_L
eval_script: bash ./eval/tasks/squad_qg/eval.sh
hidden_dropout_prob: 0.1
in_tokens: False
incr_every_n_steps: 100
incr_ratio: 2.0
init_checkpoint: None
init_loss_scaling: 128.0
init_pretraining_params: ernie_gen_base/params
is_distributed: True
label_smooth: 0.1
learning_rate: 2.5e-05
length_penalty: 1.0
lr_scheduler: linear_warmup_decay
max_dec_len: 48
max_seq_len: 400
max_dec_len: 48
max_seq_len: 400
max_src_len: 400
max_tgt_len: 96
noise_prob: 0.7
num_iteration_per_drop_scope: 1
pred_batch_size: 0
pred_set: ./datasets/squad_qg//pred.tsv
random_noise: True
random_seed: 93001
role_type_size: 0
save_and_valid_by_epoch: True
save_steps: 10000
skip_steps: 10
src_do_lower_case: True
src_tokenizer: FullTokenizer
src_vocab_path: None
stream_job: None
task_type: normal
test_set: ./datasets/squad_qg//test.tsv
tgt_type_id: 3
tokenized_input: True
tokenizer: FullTokenizer
train_set: ./datasets/squad_qg//train.tsv
turn_type_size: 0
use_cuda: True
use_dynamic_loss_scaling: False
use_fast_executor: True
use_fp16: False
use_multi_gpu_test: True
validation_steps: 1000
verbose: True
vocab_path: ernie_gen_base/vocab.txt
warmup_proportion: 0.1
weight_decay: 0.01
weight_sharing: True
------------------------------------------------
attention_probs_dropout_prob: 0.1
hidden_act: gelu
hidden_dropout_prob: 0.1
hidden_size: 768
initializer_range: 0.02
intermediate_size: 3072
max_position_embeddings: 1024
num_attention_heads: 12
num_hidden_layers: 12
type_vocab_size: 4
vocab_size: 30522
------------------------------------------------
Device count: 1, gpu_id: 0
Num train examples: 75722
Max train steps: 757220
Num warmup steps: 75722
Theoretical memory usage in training: 10074.366 - 10554.098 MB
args.is_distributed: True
worker_endpoints:['172.16.173.123:6170'] trainers_num:1 current_endpoint:172.16.173.123:6170               trainer_id:0


API is deprecated since 2.0.0 Please use FleetAPI instead.
WIKI: https://github.com/PaddlePaddle/Fleet/blob/develop/markdown_doc/transpiler




W0609 12:27:54.821136 19909 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 11.3, Runtime API Version: 10.0
W0609 12:27:54.823410 19909 device_context.cc:245] device: 0, cuDNN Version: 7.6.
I0609 12:27:55.246949 19909 rpc_client.h:107] init rpc client with trainer_id 0
Load pretraining parameters from ernie_gen_base/params.
I0609 12:27:56.123220 19909 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0609 12:27:56.197180 19909 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0609 12:27:56.563462 19909 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0609 12:27:56.644340 19909 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 1
/home/test/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py:789: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "./run_seq2seq.py", line 313, in <module>
    main(args)
  File "./run_seq2seq.py", line 264, in main
    train_exe.run(fetch_list=[])
  File "/home/test/anaconda3/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 302, in run
    return_numpy=return_numpy)
  File "/home/test/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 790, in run
    six.reraise(*sys.exc_info())
  File "/home/test/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/test/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 785, in run
    use_program_cache=use_program_cache)
  File "/home/test/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 850, in _run_impl
    return_numpy=return_numpy)
  File "/home/test/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 684, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
3   paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, long>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::details::ComputationOpHandle::RunImpl()
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
11  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
12  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
13  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/test/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/test/anaconda3/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/test/ERNIE/ernie-gen/model/ernie.py", line 139, in _gen_input
    emb_out = emb_out + emb if emb_out else emb
  File "/home/test/ERNIE/ernie-gen/model/ernie.py", line 139, in _gen_input
    emb_out = emb_out + emb if emb_out else emb
  File "/home/test/ERNIE/ernie-gen/model/ernie.py", line 173, in encode
    query_emb_out, n_head_query_attn_mask = self._gen_input(emb_ids[1], input_mask[1])
  File "/home/test/ERNIE/ernie-gen/model/ernie.py", line 228, in _build_model
    self._enc_out = self.encode(emb_ids, input_mask, gather_idx, remove_query=False)
  File "/home/test/ERNIE/ernie-gen/model/ernie.py", line 128, in __init__
    self._build_model(emb_ids, input_mask, gather_idx)
  File "/home/test/ERNIE/ernie-gen/finetune/seq2seq.py", line 159, in create_model
    task_type=self.task_type)
  File "./run_seq2seq.py", line 125, in main
    train_pyreader, graph_vars = ernie_gen.create_model()
  File "./run_seq2seq.py", line 313, in <module>
    main(args)

----------------------
Error Message Summary:
----------------------
Error: When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::dims, or Tensor::Resize has been called first. The Tensor's shape is [-1, 12, 768] now
  [Hint: Expected numel() >= 0, but received numel():-9216 < 0:0.] at (/paddle/paddle/fluid/framework/tensor.cc:45)
  [operator < elementwise_add > error]
terminate called without an active exception
W0609 12:27:57.065218 19984 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0609 12:27:57.065241 19984 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0609 12:27:57.065248 19984 init.cc:214] The detail failure signal is:

W0609 12:27:57.065258 19984 init.cc:217] *** Aborted at 1623241677 (unix time) try "date -d @1623241677" if you are using GNU date ***
W0609 12:27:57.067502 19984 init.cc:217] PC: @                0x0 (unknown)
W0609 12:27:57.067590 19984 init.cc:217] *** SIGABRT (@0x3e800004dc5) received by PID 19909 (TID 0x7fc601ed4700) from PID 19909; stack trace: ***
W0609 12:27:57.069734 19984 init.cc:217]     @     0x7fc73321f890 (unknown)
W0609 12:27:57.071744 19984 init.cc:217]     @     0x7fc732e5ae97 gsignal
W0609 12:27:57.073776 19984 init.cc:217]     @     0x7fc732e5c801 abort
W0609 12:27:57.075096 19984 init.cc:217]     @     0x7fc709a82892 __gnu_cxx::__verbose_terminate_handler()
W0609 12:27:57.076014 19984 init.cc:217]     @     0x7fc709a80f69 __cxxabiv1::__terminate()
W0609 12:27:57.077248 19984 init.cc:217]     @     0x7fc709a80fab std::terminate()
W0609 12:27:57.078239 19984 init.cc:217]     @     0x7fc709a80c7c __gxx_personality_v0
W0609 12:27:57.079216 19984 init.cc:217]     @     0x7fc71957abc8 _Unwind_ForcedUnwind_Phase2
W0609 12:27:57.080211 19984 init.cc:217]     @     0x7fc71957aeae _Unwind_ForcedUnwind
W0609 12:27:57.081902 19984 init.cc:217]     @     0x7fc73321df10 __GI___pthread_unwind
W0609 12:27:57.083508 19984 init.cc:217]     @     0x7fc733215ae5 __pthread_exit
W0609 12:27:57.084079 19984 init.cc:217]     @     0x562d02a8fa09 PyThread_exit_thread
W0609 12:27:57.084221 19984 init.cc:217]     @     0x562d02929d12 PyEval_RestoreThread.cold.739
W0609 12:27:57.086426 19984 init.cc:217]     @     0x7fc6de79a889 pybind11::gil_scoped_release::~gil_scoped_release()
W0609 12:27:57.086639 19984 init.cc:217]     @     0x7fc6de7470e4 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9operators6reader22LoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE60_bIS9_SG_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESY_
W0609 12:27:57.088801 19984 init.cc:217]     @     0x7fc6de7b8c41 pybind11::cpp_function::dispatcher()
W0609 12:27:57.089345 19984 init.cc:217]     @     0x562d029d8c54 _PyCFunction_FastCallDict
W0609 12:27:57.089700 19984 init.cc:217]     @     0x562d02a60c0e call_function
W0609 12:27:57.090265 19984 init.cc:217]     @     0x562d02a8375a _PyEval_EvalFrameDefault
W0609 12:27:57.090816 19984 init.cc:217]     @     0x562d02a5bd58 PyEval_EvalCodeEx
W0609 12:27:57.091143 19984 init.cc:217]     @     0x562d02a5c8e6 function_call
W0609 12:27:57.091691 19984 init.cc:217]     @     0x562d029d8a5e PyObject_Call
W0609 12:27:57.092248 19984 init.cc:217]     @     0x562d02a84e37 _PyEval_EvalFrameDefault
W0609 12:27:57.092581 19984 init.cc:217]     @     0x562d02a5ac5b fast_function
W0609 12:27:57.092916 19984 init.cc:217]     @     0x562d02a60b95 call_function
W0609 12:27:57.093463 19984 init.cc:217]     @     0x562d02a8375a _PyEval_EvalFrameDefault
W0609 12:27:57.093794 19984 init.cc:217]     @     0x562d02a5ac5b fast_function
W0609 12:27:57.094127 19984 init.cc:217]     @     0x562d02a60b95 call_function
W0609 12:27:57.094672 19984 init.cc:217]     @     0x562d02a8375a _PyEval_EvalFrameDefault
W0609 12:27:57.095175 19984 init.cc:217]     @     0x562d02a5b2db _PyFunction_FastCallDict
W0609 12:27:57.095664 19984 init.cc:217]     @     0x562d029d901f _PyObject_FastCallDict
W0609 12:27:57.096171 19984 init.cc:217]     @     0x562d029ddaa3 _PyObject_Call_Prepend
W0609 12:27:57.096171 19984 init.cc:217]     @     0x562d029ddaa3 _PyObject_Call_Prepend
```

I don't know what's going on, I've tried with different paddle versions (until version 2.0.2, version 2.1.0 give me some errors). At the begining I though that maybe it was some GPU memory problems (I only have one GPU with ~12GB), but I reduced the batch size to 1 and max_seq_len, max_src_len to 400, and now the theorical memory in usage in training is 10074.366 - 10554.098 MB. I've tried to predict with the pretrained ernie-gen, and it works, but, as it is supposed, the predictions are not fine. I appreciate your help.

**Comment by satkatai** [comment]
Hi @cberrioa ,

I am not sure about the problem you are facing, but can you please send the script to predict with ernie-gen pre-trained models on my own text?
