### ISSUE TITLE
Can't open VCR_resnet101_faster_rcnn_genome_pickle2.lmdb: ValueError: unsupported pickle protocol: 3

### ISSUE THREAD

**Issue by greeksharifa** [PaddlePaddle/ERNIE#718]
I want to run the VCR inference(run_inference.sh)  in python 2.7, however, this error occurred:

```
Traceback (most recent call last):
  File "finetune.py", line 868, in <module>
    main(args)
  File "finetune.py", line 802, in main
    graph_vars=model_outputs)
  File "finetune.py", line 436, in predict_wrapper
    epoch=args.epoch)
  File "/home/ywjang/ERNIE-repro/ernie-vil/reader/vcr_finetuning.py", line 414, in __init__
    ImageFeaturesH5Reader(task_conf['feature_lmdb_path'])
  File "/home/ywjang/ERNIE-repro/ernie-vil/reader/_image_features_reader.py", line 34, in __init__
    self._image_ids = pickle.loads(txn.get('keys'.encode()))
ValueError: unsupported pickle protocol: 3
```

feature_path is `u'./data/vcr/VCR_resnet101_faster_rcnn_genome_pickle2.lmdb')`,

And,  the error `ValueError: unsupported pickle protocol: 3` occur usually with pickle protocol version, so I tried to convert the protocol of lmdb(mdb) files:

```
pickle.dump(pickle.load(open('data.mdb', 'rb')), open('data2.mdb', 'wb'), protocol=2)
```

And now, another error occurred:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.UnpicklingError: invalid load key, '\x00'.
```

Is this github code working?

p.s. in python 3.5, another error occurred:

```
use gt featurre
Traceback (most recent call last):
  File "finetune.py", line 868, in <module>
    main(args)
  File "finetune.py", line 802, in main
    graph_vars=model_outputs)
  File "finetune.py", line 436, in predict_wrapper
    epoch=args.epoch)
  File "/home/ywjang/ERNIE-repro/ernie-vil/reader/vcr_finetuning.py", line 424, in __init__
    epoch, is_test, feature_reader_dict, random_seed, task_index, len(task_conf_group)))
  File "/home/ywjang/ERNIE-repro/ernie-vil/reader/vcr_finetuning.py", line 186, in __init__
    self.tokenize()
  File "/home/ywjang/ERNIE-repro/ernie-vil/reader/vcr_finetuning.py", line 255, in tokenize
    q_str = " ".join(tokens_a)
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by yinweichong** [comment]
#596 
refer this issue

i paste convert example code here

```
env = lmdb.open(new_path, map_size=1099511627776)
txn = env.begin(write=True)
env_src = lmdb.open("VCR_resnet101_faster_rcnn_genome.lmdb", max_readers=1, readonly=True)
with env_src.begin(write=False) as txn_src:
    for i, (key, value) in enumerate(txn_src.cursor().iterprev()):
        txn.put(key, pickle.dumps(pickle.loads(value), protocol=2))
txn.commit()
```
