### ISSUE TITLE
An error occurred when I run run_dbqa.sh

### ISSUE THREAD

**Issue by lxy1108** [PaddlePaddle/ERNIE#74]
The error is:
Traceback (most recent call last):
  File "run_classifier.py", line 276, in <module>
    main(args)
  File "run_classifier.py", line 195, in main
    train_exe.run(fetch_list=[])
  File "/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 303, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator matmul error.
Python Callstacks: 
  File "/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 4771, in matmul
    'alpha': float(alpha),
  File "/media/lixinyi/Office/LARK-develop/ERNIE/model/ernie.py", line 116, in _build_model
    x=input_mask, y=input_mask, transpose_y=True)
  File "/media/lixinyi/Office/LARK-develop/ERNIE/model/ernie.py", line 82, in __init__
    self._build_model(src_ids, position_ids, sentence_ids, input_mask)
  File "/media/lixinyi/Office/LARK-develop/ERNIE/finetune/classifier.py", line 49, in create_model
    use_fp16=args.use_fp16)
  File "run_classifier.py", line 94, in main
    ernie_config=ernie_config)
  File "run_classifier.py", line 276, in <module>
    main(args)
C++ Callstacks: 
CUBLAS: execution failed,  at [/paddle/paddle/fluid/operators/math/blas_impl.cu.h:50]

**Comment by LittlePill** [comment]
机器上只有一块GPU 如何修改代码呢

**Comment by guoshengCS** [comment]
这个可能是GPU和CUDA环境的问题，可否试下跑下Paddle [book](https://github.com/PaddlePaddle/book)中的简单模型确认下是否有同样的问题
