### ISSUE TITLE
pretrain.py raising AttributeError: 'PosixPath' object has no attribute 'tell'

### ISSUE THREAD

**Issue by peppocola** [PaddlePaddle/ERNIE#765]
When I try to run this command :
```
!python ./demo/pretrain/pretrain.py \
--data_dir "path/to/train_data.gz" \
--from_pretrained "ernie-2.0-en" --save_dir "path/to/dir/" \
--max_seqlen 100
```

I get this error :

```
File "./demo/pretrain/pretrain.py", line 346, in <module>
    model = ErnieModelForPretraining.from_pretrained(args.from_pretrained)
  File "/content/ERNIE/ernie/modeling_ernie.py", line 293, in from_pretrained
    m = P.load(state_dict_path)
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/io.py", line 928, in load
    with _open_file_buffer(path, 'rb') as f:
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/io.py", line 111, in _open_file_buffer
    return _buffer_reader(path_or_buffer)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/io.py", line 86, in __init__
    self.initial_tell = self.buffer.tell()
AttributeError: 'PosixPath' object has no attribute 'tell'
```
How should I fix it?

**Comment by peppocola** [comment]
full trace here: 
```
/content/ERNIE/propeller/paddle/__init__.py:41: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  log.warn('enabling old_styled_ckpt')
[WARNING] 2021-11-13 15:47:54,621 [ __init__.py:   41]:	enabling old_styled_ckpt
[INFO] 2021-11-13 15:47:55,016 [tokenizing_ernie.py:  102]:    get pretrain dir from https://ernie-github.cdn.bcebos.com/model-ernie2.0-en.1.tar.gz
DEBUG:filelock:Attempting to acquire lock 140395529425936 on /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e.lock
DEBUG:filelock:Lock 140395529425936 acquired on /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e.lock
[DEBUG] 2021-11-13 15:47:55,019 [file_utils.py:   48]:    https://ernie-github.cdn.bcebos.com/model-ernie2.0-en.1.tar.gz cached in /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e
DEBUG:filelock:Attempting to release lock 140395529425936 on /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e.lock
DEBUG:filelock:Lock 140395529425936 released on /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e.lock
[DEBUG] 2021-11-13 15:47:55,039 [tokenizing_ernie.py:  157]:    regex: (\[CLS\])|(\[PAD\])|(\[MASK\])|(\[SEP\])|(\[UNK\])|([a-zA-Z0-9]+|\S)
[INFO] 2021-11-13 15:47:55,040 [ pretrain.py:  158]:	read from /content/drive/MyDrive/hate_data/train_data.gz
[INFO] 2021-11-13 15:47:55,041 [modeling_ernie.py:  267]:    get pretrain dir from https://ernie-github.cdn.bcebos.com/model-ernie2.0-en.1.tar.gz
DEBUG:filelock:Attempting to acquire lock 140395527800208 on /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e.lock
DEBUG:filelock:Lock 140395527800208 acquired on /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e.lock
[DEBUG] 2021-11-13 15:47:55,041 [file_utils.py:   48]:    https://ernie-github.cdn.bcebos.com/model-ernie2.0-en.1.tar.gz cached in /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e
DEBUG:filelock:Attempting to release lock 140395527800208 on /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e.lock
DEBUG:filelock:Lock 140395527800208 released on /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e.lock
[DEBUG] 2021-11-13 15:47:55,042 [modeling_ernie.py:  310]:    init ErnieModel with config: {'attention_probs_dropout_prob': 0.1, 'hidden_act': 'gelu', 'hidden_dropout_prob': 0.1, 'hidden_size': 768, 'initializer_range': 0.02, 'max_position_embeddings': 512, 'num_attention_heads': 12, 'num_hidden_layers': 12, 'sent_type_vocab_size': 4, 'task_type_vocab_size': 16, 'vocab_size': 30522}
W1113 15:47:55.043432   725 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 3.7, Driver API Version: 11.2, Runtime API Version: 11.1
W1113 15:47:55.047025   725 device_context.cc:465] device: 0, cuDNN Version: 7.6.
W1113 15:47:55.409149   725 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.1, but CUDNN version in your machine is 7.6, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
[INFO] 2021-11-13 15:47:56,428 [modeling_ernie.py:  285]:    loading pretrained model from /root/.paddle-ernie-cache/43cf6490a67bdc70e4423b84cf0bf82e
/usr/local/lib/python3.7/dist-packages/paddle/distributed/parallel.py:136: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
Traceback (most recent call last):
  File "./demo/pretrain/pretrain.py", line 346, in <module>
    model = ErnieModelForPretraining.from_pretrained(args.from_pretrained)
  File "/content/ERNIE/ernie/modeling_ernie.py", line 293, in from_pretrained
    m = P.load(state_dict_path)
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/io.py", line 928, in load
    with _open_file_buffer(path, 'rb') as f:
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/io.py", line 111, in _open_file_buffer
    return _buffer_reader(path_or_buffer)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/io.py", line 86, in __init__
    self.initial_tell = self.buffer.tell()
AttributeError: 'PosixPath' object has no attribute 'tell'
```

**Comment by Meiyim** [comment]
this is a paddle 2.2 issue, `paddle.load` / `paddle.save`, no longer accept `pathlib.Path` object as argument.
this is fixed in #763 .

**Comment by musitafa0032** [comment]
I still have this issue, how do you solve it?

**Comment by l-i-p-f** [comment]
Assuming you have error like this : 
```
  File "/content/ERNIE/ernie/modeling_ernie.py", line 293, in from_pretrained
    m = P.load(state_dict_path)
```
One way you can try : 
1. vi /content/ERNIE/ernie/modeling_ernie.py
2. change line 293 from `m = P.load(state_dict_path)` to `m = P.load(state_dict_path.as_posix())`
