### ISSUE TITLE
安装后第一次跑报AttributeError: 'WindowsPath' object has no attribute 'tell'

### ISSUE THREAD

**Issue by Daminan0919** [PaddlePaddle/ERNIE#818]
应该是执行：model = ErnieModel.from_pretrained('ernie-1.0')时报如下错，windows中的pycharm里跑的，版本2.3.0

[INFO] 2022-05-20 14:36:48,313 [modeling_ernie.py:  267]:    get pretrain dir from https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
[INFO] 2022-05-20 14:36:54,157 [modeling_ernie.py:  285]:    loading pretrained model from C:\Users\xwhmajun\.paddle-ernie-cache\466eabcffd6d6a83ae9cb97dd1a167bd
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-7cbf84344b97>", line 1, in <module>
    runfile('E:/telecom/telework/python/geekbangpython-master/geekbangpython-master/chinese_match/paddle_baidu.py', wdir='E:/telecom/telework/python/geekbangpython-master/geekbangpython-master/chinese_match')
  File "D:\Program Files\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/telecom/telework/python/geekbangpython-master/geekbangpython-master/chinese_match/paddle_baidu.py", line 18, in <module>
    model = ErnieModel.from_pretrained('ernie-1.0')
  File "D:\anaconda3\lib\site-packages\ernie\ernie\modeling_ernie.py", line 293, in from_pretrained
    m = P.load(state_dict_path)
  File "C:\Users\xwhmajun\AppData\Roaming\Python\Python39\site-packages\paddle\framework\io.py", line 947, in load
    with _open_file_buffer(path, 'rb') as f:
  File "C:\Users\xwhmajun\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\io.py", line 111, in _open_file_buffer
    return _buffer_reader(path_or_buffer)
  File "C:\Users\xwhmajun\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\io.py", line 86, in __init__
    self.initial_tell = self.buffer.tell()
AttributeError: 'WindowsPath' object has no attribute 'tell'

**Comment by webYFDT** [comment]
可以参考一下 https://toscode.gitee.com/paddlepaddle/Paddle/issues/I4QBUH
