### ISSUE TITLE
enric_encoder.py 报错 Invoke operator fill_constant error 和 Windows not support stack backtrace yet.

### ISSUE THREAD

**Issue by Walleclipse** [PaddlePaddle/ERNIE#87]
你好，我运行 enric_encoder.py 到 exe.run(startup_prog) 会出现错误，具体错误信息如下：

 ```
 File "C:\Users\Python\Python36\site-packages\paddle\fluid\executor.py", line 591, in _run
   exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks: 
  File "C:\Users\Python\Python36\site-packages\paddle\fluid\framework.py", line 1382, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\Python\Python36\site-packages\paddle\fluid\initializer.py", line 167, in __call__
    stop_gradient=True)
  File "C:\Users\Python\Python36\site-packages\paddle\fluid\framework.py", line 1300, in create_parameter
    initializer(param, self)
  File "C:\Users\Python\Python36\site-packages\paddle\fluid\layer_helper.py", line 339, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "C:\Users\Python\Python36\site-packages\paddle\fluid\layer_helper.py", line 424, in append_bias_op
    attr=bias_attr, shape=size, dtype=input_var.dtype, is_bias=True)
  File "C:\Users\Python\Python36\site-packages\paddle\fluid\layers\nn.py", line 297, in fc
    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)
  File "D:\pycharm\course\IR_chat\LARK-develop\LARK-develop\ERNIE\model\ernie.py", line 155, in get_pooled_output
    bias_attr="pooled_fc.b_0")
  File "D:/pycharm/course/IR_chat/LARK-develop/LARK-develop/ERNIE/ernie_encoder.py", line 79, in create_model
    cls_feats = ernie.get_pooled_output()
  File "D:/pycharm/course/IR_chat/LARK-develop/LARK-develop/ERNIE/ernie_encoder.py", line 131, in main
    args, pyreader_name='reader', ernie_config=ernie_config)
  File "D:/pycharm/course/IR_chat/LARK-develop/LARK-develop/ERNIE/ernie_encoder.py", line 185, in <module>
    main(args)
C++ Callstacks: 
Enforce failed. Expected allocating <= available, but received allocating:11440875110 > available:11143610112.
Insufficient GPU memory to allocation. at [D:\1.3.2\paddle\paddle\fluid\platform\gpu_info.cc:216]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.
W0411 20:25:15.478150 40984 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 52, Driver API Version: 9.0, Runtime API Version: 8.0
W0411 20:25:15.478150 40984 device_context.cc:271] device: 0, cuDNN Version: 7.0.
W0411 20:25:15.478150 40984 device_context.cc:295] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.1, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
```

这个问题该怎么解决呢？谢谢

**Comment by tianxin1860** [comment]
显存不足，可以改小 batch_size 试试

**Comment by Walleclipse** [comment]
你好，好像并不是显存不足。我把batch_size设置为2
`data_g.add_arg("batch_size", int, 2, "Total examples' number in batch for training.")`
并且有20多G显存
![image](https://user-images.githubusercontent.com/37198574/55975188-ff195200-5cbb-11e9-8e7d-ed0131606320.png)
我怀疑这个是windows系统导致的。
```
Insufficient GPU memory to allocation. at [D:\1.3.2\paddle\paddle\fluid\platform\gpu_info.cc:216]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.
```
有什么解决方案么？

**Comment by Walleclipse** [comment]
你好，好像并不是显存不足。我把batch_size设置为2
`data_g.add_arg("batch_size", int, 2, "Total examples' number in batch for training.")`
并且有20多G显存
![image](https://user-images.githubusercontent.com/37198574/55975188-ff195200-5cbb-11e9-8e7d-ed0131606320.png)
我怀疑这个是windows系统导致的。
```
Insufficient GPU memory to allocation. at [D:\1.3.2\paddle\paddle\fluid\platform\gpu_info.cc:216]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.
```
有什么解决方案么？

**Comment by Walleclipse** [comment]
你好，好像并不是显存不足。我把batch_size设置为2
`data_g.add_arg("batch_size", int, 2, "Total examples' number in batch for training.")`
并且有20多G显存
![image](https://user-images.githubusercontent.com/37198574/55975188-ff195200-5cbb-11e9-8e7d-ed0131606320.png)
我怀疑这个是windows系统导致的。
```
Insufficient GPU memory to allocation. at [D:\1.3.2\paddle\paddle\fluid\platform\gpu_info.cc:216]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.
```
有什么解决方案么？

**Comment by Walleclipse** [comment]
补充一下，在CPU下可以运行，GPU就不行。但应该不是显存问题，很可能是windows操作系统导致的。有什么解决方案么？

**Comment by sneaxiy** [comment]
您这个问题确实是显存不足引起的。您可以打下log，GLOG_vmodule=operator=4，然后把log贴出来。您是跑startup就挂了还是main就挂了。Windows系统为了自己的GUI，会额外占显存，所以Paddle不能用太多显存。

**Comment by Walleclipse** [comment]
你好！非常感谢！确实可能是显存不足引起的，我换了个显卡就可以运行`enric_encoder.py` 了。之前没注意，非常不好意思。
随后，我想fine-tune的时候，试图运行`run_classifier.py` 时候，报了如下这个错误。
```
Theoretical memory usage in training: 30071.768 - 31503.757 MB
Load pretraining parameters from ERNIE_stable-1.0.1/params.
Traceback (most recent call last):
  File "D:/pycharm/LARK-develop/LARK-develop/ERNIE/run_classifier.py", line 280, in <module>
    main(args)
  File "D:/pycharm/LARK-develop/LARK-develop/ERNIE/run_classifier.py", line 182, in main
    main_program=train_program)
  File "C:\Users\AppData\Roaming\Python\Python36\site-packages\paddle\fluid\parallel_executor.py", line 191, in __init__
    local_scopes, exec_strategy, build_strategy)
paddle.fluid.core.EnforceNotMet: Not compiled with CUDA at [D:\1.3.2\paddle\paddle\fluid\framework\parallel_executor.cc:250]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.
```
似乎是运行到 如下一步 的时候报错了。这个是 分布式 导致的么？
`train_exe = fluid.ParallelExecutor(use_cuda=args.use_cuda, loss_name=graph_vars["loss"].name, exec_strategy=exec_strategy,main_program=train_program)`
非常感谢！

**Comment by sneaxiy** [comment]
Windows系统不支持ParallelExecutor这个API，您可以使用Executor。

**Comment by Walleclipse** [comment]
好的，谢谢了。我试试

**Comment by Walleclipse** [comment]
你好，我试图改成了Executer这个API，但是由于我对paddlepaddle不熟，所以不知道改的对不对。能帮我看一下么？
```
if args.do_train:
	exec_strategy = fluid.ExecutionStrategy()
	if args.use_fast_executor:
		exec_strategy.use_experimental_executor = True
	exec_strategy.num_threads = dev_count
	exec_strategy.num_iteration_per_drop_scope = args.num_iteration_per_drop_scope
	# train_exe = fluid.ParallelExecutor( #ParallelExecutor
	#    use_cuda=args.use_cuda,
	#    loss_name=graph_vars["loss"].name,
	#   exec_strategy=exec_strategy,
	#  main_program=train_program)
	train_pyreader.decorate_tensor_provider(train_data_generator)
#else:
#	#train_exe = None

if args.do_train:
	train_pyreader.start()
	steps = 0
	time_begin = time.time()
	while True:
		try:
			steps += 1
			if steps % args.skip_steps != 0:
				loss_value = exe.run(
					program=train_program,
					fetch_list=[graph_vars["loss"].name],
					return_numpy=False)
```
随后我在给出的`LCQMC`数据上跑这个程序，loss 有点震荡。我不知道这个是正常的还是好我写的有点问题。acc到多少左右是比较正常的？
![image](https://user-images.githubusercontent.com/37198574/56074171-4993ef00-5de0-11e9-96fa-44fb537d47b0.png)

非常感谢！

**Comment by tianxin1860** [comment]
最优 acc 以及参数配置可以查看 README
