### ISSUE TITLE
[BUG] create_program_desc(): incompatible function arguments

### ISSUE THREAD

**Issue by cs1137195420** [PaddlePaddle/ERNIE#894]
我在运行ERINE3.0文本分类的启动训练模型时，中间能够正常打印损失和精确率的日志，但在最后一步报错了，请问这个问题该怎么解决呢？
```
Traceback (most recent call last):
  File "D:/project_hyb/20230310_中文LLM/ERNIE/applications/tasks/text_classification/run_trainer.py", line 130, in <module>
    run_trainer(_params)
  File "D:/project_hyb/20230310_中文LLM/ERNIE/applications/tasks/text_classification/run_trainer.py", line 107, in run_trainer
    trainer.do_train()
  File "D:\project_hyb\20230310_中文LLM\ERNIE\applications\tasks\text_classification\trainer\custom_dynamic_trainer.py", line 115, in do_train
    self.save_models(steps, example)
  File "D:\project_hyb\20230310_中文LLM\ERNIE\erniekit\controller\dynamic_trainer.py", line 173, in save_models
    phase="save_inference")
  File "C:\ProgramData\Anaconda3\envs\erine3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\Anaconda3\envs\erine3\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\erine3\lib\site-packages\paddle\fluid\framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "D:\project_hyb\20230310_中文LLM\ERNIE\erniekit\common\jit_wenxin.py", line 37, in trace
    out = _trace_wenxin(layer, inputs, phase="save_inference")
  File "C:\ProgramData\Anaconda3\envs\erine3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\Anaconda3\envs\erine3\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\erine3\lib\site-packages\paddle\fluid\framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "D:\project_hyb\20230310_中文LLM\ERNIE\erniekit\common\jit_wenxin.py", line 75, in _trace_wenxin
    fetch_prefix, tmp_prefix)
TypeError: create_program_desc(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.libpaddle.ProgramDescTracer, arg0: List[paddle.fluid.libpaddle.VarBase], arg1: str, arg2: List[paddle.fluid.libpaddle.VarBase], arg3: str, arg4: str) -> Tuple[paddle::framework::ProgramDesc, List[str], List[str], List[paddle.fluid.libpaddle.VarBase]]

Invoked with: <paddle.fluid.libpaddle.ProgramDescTracer object at 0x000001EF6E35AD70>, [Tensor(shape=[8, 168], dtype=int64, place=Place(gpu:0), stop_gradient=True,
       [[1    , 96   , 1198 , ..., 0    , 0    , 0    ],
        [1    , 242  , 213  , ..., 0    , 0    , 0    ],
        [1    , 768  , 136  , ..., 0    , 0    , 0    ],
        ...,
        [1    , 458  , 143  , ..., 0    , 0    , 0    ],
        [1    , 208  , 1000 , ..., 0    , 0    , 0    ],
        [1    , 634  , 692  , ..., 1260 , 12044, 2    ]]), Tensor(shape=[8, 168], dtype=int64, place=Place(gpu:0), stop_gradient=True,
       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])], 'feed_', [Tensor(shape=[8, 2], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [[0.00053400, 0.99946600],
        [0.00079978, 0.99920028],
        [0.00063857, 0.99936146],
        [0.99457103, 0.00542894],
        [0.00071414, 0.99928588],
        [0.99798137, 0.00201871],
        [0.99878722, 0.00121276],
        [0.99851328, 0.00148677]])], 'fetch_', 't_'
```

**Comment by julianzhao88** [comment]
我也遇到这个问题，没人知道怎么解决吗？

**Comment by cs1137195420** [comment]
> 我也遇到这个问题，没人知道怎么解决吗？

你也是这个问题吗？你用的是哪个版本的paddle呢

**Comment by julianzhao88** [comment]
paddlepaddle-gpu     2.4.2

**Comment by cs1137195420** [comment]
> paddlepaddle-gpu 2.4.2

我之前报错的时候装的也是这个版本，估计是版本太新导致的。我翻了下这个仓库的issue，官方快一年没更新了，之前用paddlepaddle-gpu 2.3的人好像没出过这个问题。
我后来改用`conda install paddlepaddle-gpu==2.3.2 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`装了个2.3的环境，可以跑通文本生成的例子，文本分类我没有试，但我想应该是同样的问题。

**Comment by julianzhao88** [comment]
改成2.3.2可以了，

> > paddlepaddle-gpu 2.4.2
> 
> 我之前报错的时候装的也是这个版本，估计是版本太新导致的。我翻了下这个仓库的issue，官方快一年没更新了，之前用paddlepaddle-gpu 2.3的人好像没出过这个问题。 我后来改用`conda install paddlepaddle-gpu==2.3.2 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`装了个2.3的环境，可以跑通文本生成的例子，文本分类我没有试，但我想应该是同样的问题。

改成2.3.2可以了，谢谢！

**Comment by ob6123** [comment]
改成2.3.2又报了另一个错误no model paddle.fluid.libpaddle
