### ISSUE TITLE
run  sample throws error with official paddle docker image

### ISSUE THREAD

**Issue by RockNHawk** [PaddlePaddle/ERNIE#908]
**Describe the bug**

**To Reproduce**
docker run -it --name paddle242 paddlepaddle/paddle:2.4.2-gpu-cuda11.7-cudnn8.4-trt8.4
git clone https://github.com/PaddlePaddle/ERNIE.git
cd ERNIE
cd ./applications/models_hub
sh download_ernie_3.0_base_ch.sh
cd ../../
cd ./applications/tasks/text_generation

python run_infer.py --param_path ./examples/cls_ernie_gen_infilling_ch_infer.json

**Error  output**

**throws  No module named 'sentencepiece' error**

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py:635: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."
INFO: 06-04 09:21:13: params.py:43 * 140527343998784 ./examples/cls_ernie_gen_infilling_ch_infer.json

ERROR: 06-04 09:21:13: register.py:106 * 140527343998784 error in import modules
ERROR: 06-04 09:21:13: register.py:107 * 140527343998784 traceback.format_exc():
Traceback (most recent call last):
  File "../../../erniekit/common/register.py", line 103, in import_modules
    importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../../../erniekit/data/tokenizer/tokenization_wp.py", line 32, in <module>
    import sentencepiece as sp
ModuleNotFoundError: No module named 'sentencepiece'

ERROR: 06-04 09:21:13: register.py:106 * 140527343998784 error in import modules
ERROR: 06-04 09:21:13: register.py:107 * 140527343998784 traceback.format_exc():
Traceback (most recent call last):
  File "../../../erniekit/common/register.py", line 103, in import_modules
    importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../../../erniekit/data/tokenizer/tokenization_erniem.py", line 34, in <module>
    import sentencepiece as spm
ModuleNotFoundError: No module named 'sentencepiece'

ERROR: 06-04 09:21:13: register.py:106 * 140527343998784 error in import modules
ERROR: 06-04 09:21:13: register.py:107 * 140527343998784 traceback.format_exc():
Traceback (most recent call last):
  File "../../../erniekit/common/register.py", line 103, in import_modules
    importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../../../erniekit/data/tokenizer/tokenization_mix.py", line 31, in <module>
    from .tokenization_wp import FullTokenizer
  File "../../../erniekit/data/tokenizer/tokenization_wp.py", line 32, in <module>
    import sentencepiece as sp
ModuleNotFoundError: No module named 'sentencepiece'

ERROR: 06-04 09:21:13: register.py:106 * 140527343998784 error in import modules
ERROR: 06-04 09:21:13: register.py:107 * 140527343998784 traceback.format_exc():
Traceback (most recent call last):
  File "../../../erniekit/common/register.py", line 103, in import_modules
    importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../../../erniekit/data/tokenizer/tokenization_spm.py", line 34, in <module>
    import sentencepiece as spm
ModuleNotFoundError: No module named 'sentencepiece'

ERROR: 06-04 09:21:13: register.py:106 * 140527343998784 error in import modules
ERROR: 06-04 09:21:13: register.py:107 * 140527343998784 traceback.format_exc():
Traceback (most recent call last):
  File "../../../erniekit/common/register.py", line 103, in import_modules
    importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../../../erniekit/data/tokenizer/mrc_tokenizer.py", line 21, in <module>
    import sentencepiece as sp
ModuleNotFoundError: No module named 'sentencepiece'

ERROR: 06-04 09:21:13: register.py:106 * 140527343998784 error in import modules
ERROR: 06-04 09:21:13: register.py:107 * 140527343998784 traceback.format_exc():
Traceback (most recent call last):
  File "../../../erniekit/common/register.py", line 103, in import_modules
    importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../../../erniekit/data/tokenizer/doie_ernie_tiny_tokenizer.py", line 18, in <module>
    import sentencepiece as sp
ModuleNotFoundError: No module named 'sentencepiece'

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py:635: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."
INFO: 06-04 09:26:40: params.py:43 * 139652022368064 ./examples/cls_ernie_gen_infilling_ch_infer.json

ERROR: 06-04 09:21:13: register.py:124 * 140527343998784 error in import ernie_gen_infilling_dataset_reader
ERROR: 06-04 09:21:13: register.py:125 * 140527343998784 traceback.format_exc():
Traceback (most recent call last):
  File "../../../erniekit/common/register.py", line 121, in import_new_module
    importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ERNIE/applications/tasks/text_generation/data_set_reader/ernie_gen_infilling_dataset_reader.py", line 23, in <module>
    from paddle.fluid.core_avx import PaddleTensor, PaddleDType
ModuleNotFoundError: No module named 'paddle.fluid.core_avx'

ERROR: 06-04 09:21:13: register.py:124 * 140527343998784 error in import ernie_infilling_generation
ERROR: 06-04 09:21:13: register.py:125 * 140527343998784 traceback.format_exc():
Traceback (most recent call last):
  File "../../../erniekit/common/register.py", line 121, in import_new_module
    importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ERNIE/applications/tasks/text_generation/model/ernie_infilling_generation.py", line 21, in <module>
    from erniekit.metrics.gen_eval import GenerationEval
  File "../../../erniekit/metrics/gen_eval.py", line 25, in <module>
    from erniekit.data.tokenizer.tokenization_wp import BasicTokenizer
  File "../../../erniekit/data/tokenizer/tokenization_wp.py", line 32, in <module>
    import sentencepiece as sp
ModuleNotFoundError: No module named 'sentencepiece'

# tried fixes

`pip install sentencepiece`

Installing collected packages: sentencepiece
Successfully installed sentencepiece-0.1.99

WARNING: 06-04 09:26:40: register.py:25 * 139652022368064 Key WordsegTokenizer already in registry tokenizer.
ERROR: 06-04 09:26:40: register.py:124 * 139652022368064 error in import ernie_gen_infilling_dataset_reader
ERROR: 06-04 09:26:40: register.py:125 * 139652022368064 traceback.format_exc():
Traceback (most recent call last):
  File "../../../erniekit/common/register.py", line 121, in import_new_module
    importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ERNIE/applications/tasks/text_generation/data_set_reader/ernie_gen_infilling_dataset_reader.py", line 23, in <module>
    from paddle.fluid.core_avx import PaddleTensor, PaddleDType
ModuleNotFoundError: No module named 'paddle.fluid.core_avx'

ERROR: 06-04 09:26:40: register.py:46 * 139652022368064 module {key} not found: {e}
Traceback (most recent call last):
  File "run_infer.py", line 60, in <module>
    dataset_reader = dataset_reader_from_params(dataset_reader_params_dict)
  File "run_infer.py", line 21, in dataset_reader_from_params
    dataset_reader.build()
  File "../../../erniekit/data/data_set_ernie3.py", line 60, in build
    dataset_reader_class = RegisterSet.data_set_reader.__getitem__(dataset_reader_name)
  File "../../../erniekit/common/register.py", line 47, in __getitem__
    raise e
  File "../../../erniekit/common/register.py", line 44, in __getitem__
    return self._dict[key]
KeyError: 'InfillingGenReader'

**Comment by RockNHawk** [comment]
Sorry, the second error seems I use gpu image but current docker with gpu not property worked.

(I use WSL2, and nvidia  CUDA supports WSL2)

I'wll follow this `Nvidia Docker on WSL2` and try again.
https://medium.com/htc-research-engineering-blog/nvidia-docker-on-wsl2-f891dfe34ab

**Comment by RockNHawk** [comment]
Also not throws error:

docker run --gpus all -it --name paddle242 paddlepaddle/paddle:2.4.2-gpu-cuda11.7-cudnn8.4-trt8.4
 
## GPU check pass
python -c "import paddle;paddle.utils.run_check()

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Running verify PaddlePaddle program ...
W0604 09:58:14.798557   142 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.7
W0604 09:58:14.807749   142 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.



export http_proxy='http://192.168.3.191:10607'   

git clone https://github.com/PaddlePaddle/ERNIE.git

cd ERNIE
cd ./applications/models_hub
ls
sh download_ernie_3.0_base_ch.sh

cd ../../
cd ./applications/tasks/text_generation

pip install sentencepiece
python run_infer.py --param_path ./examples/cls_ernie_gen_infilling_ch_infer.json

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
INFO: 06-04 09:58:49: params.py:43 * 140611369559872 ./examples/cls_ernie_gen_infilling_ch_infer.json
INFO: 06-04 09:58:49: params.py:52 * 140611369559872 {
    "dataset_reader": {
.......
WARNING: 06-04 09:58:49: register.py:25 * 140611369559872 Key WordsegTokenizer already in registry tokenizer.
ERROR: 06-04 09:58:49: register.py:124 * 140611369559872 error in import ernie_gen_infilling_dataset_reader
ERROR: 06-04 09:58:49: register.py:125 * 140611369559872 traceback.format_exc():
Traceback (most recent call last):
  File "../../../erniekit/common/register.py", line 121, in import_new_module
    importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/ERNIE/applications/tasks/text_generation/data_set_reader/ernie_gen_infilling_dataset_reader.py", line 23, in <module>
    from paddle.fluid.core_avx import PaddleTensor, PaddleDType
ModuleNotFoundError: No module named 'paddle.fluid.core_avx'

ERROR: 06-04 09:58:49: register.py:46 * 140611369559872 module {key} not found: {e}
Traceback (most recent call last):
  File "run_infer.py", line 60, in <module>
    dataset_reader = dataset_reader_from_params(dataset_reader_params_dict)
  File "run_infer.py", line 21, in dataset_reader_from_params
    dataset_reader.build()
  File "../../../erniekit/data/data_set_ernie3.py", line 60, in build
    dataset_reader_class = RegisterSet.data_set_reader.__getitem__(dataset_reader_name)
  File "../../../erniekit/common/register.py", line 47, in __getitem__
    raise e
  File "../../../erniekit/common/register.py", line 44, in __getitem__
    return self._dict[key]
KeyError: 'InfillingGenReader'
